### ISSUE TITLE
6啊大兄弟

### ISSUE THREAD

**Issue by FengLi666** [nikan1996/greenreactor#1]
我是刚来eigen做爬虫的，顺便维护下dcrawl的框架。。。大量小item上传oss速度有问题，想找个twisted的gevent reactor，一搜居然找到老哥你了，为啥内部git上找不到啊。。。

简单测了下没啥问题，但我也不懂twisted，想问下这个有啥坑吗

**Comment by LostClue** [comment]
主要是因为cpu效率上没有提升。
1. 通过 benchmark,gevent 跟 twisted 的效率没有本质上的区别。Twisted 最慢的地方在于对ssl的加解密, 因为是纯 python的 ssl 代码，这会导致cpu负载剧烈增加。
2. 对于阻塞的小 item 上传 oss速度的问题，你可以用twisted  threadpool 的形式来增加oss一块的并发量

如果要使用greenreactor：
1. 首先要在 scrapy库的运行初期添加 patch 代码
2. 对于 开启阻塞线程的情况，比如kafka库会启动 producer 和 consumer 的线程并长时间运行，需要取消gevent对 thread 的 patch。建议使用`gevent.monkey.patch_all(thread=False)`

**Comment by FengLi666** [comment]
OK，我尝试用线程池做吧
多谢啦
